gText_Birch_Welcome::
	.string "Hey, new adventurer!\n"
	.string "Welcome to the world of POKéMON!\p"
	.string "I'm BRANDON.\p"
	.string "But everyone calls me the PYRAMID\n"
	.string "KING!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "But you already knew that,\n"
	.string "am I right?\p"
	.string "Let's cut to the chase.\p"
	.string "The BATTLE PYRAMID has become\n"
	.string "more mysterious lately,\l"
	.string "far more than usual.\p"
	.string "I think this is the opportune\n"
	.string "moment to send courageous explorers\l"
	.string "in there to investigate!\p"
	.string "You'll receive a grand prize\n"
	.string "simply for entering:\l"
	.string "A lifetime supply of LUXURY BALLS!\p"
	.string "And the rules have changed.\n"
	.string "All those exotic wild POKéMON\l"
	.string "are free to catch. Hahahah!\p"
	.string "It'll be a grand time, indeed!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now...$"

gText_Birch_BoyOrGirl::
	.string "Which of these TRAINERS\n"
	.string "will tackle the challenge?$"

gText_Birch_WhatsYourName::
	.string "Excellent!\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "How grand!\p"
	.string "You're {PLAYER}{KUN} who's coming to\n"
	.string "explore my new BATTLE PYRAMID.\l"
	.string "I'm counting on you!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your grand adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where danger,\l"
	.string "adventure, and excitement await!\p"
	.string "I'll be expecting you later.\n"
	.string "Come see me atop the PYRAMID.\p"
	.string "$"
